### ISSUE TITLE
To load the flashcards/deck from local json files

### ISSUE THREAD

**Issue by t-cool** [t-cool/flashcards-for-developers#1]
Thanks to @dhamaniasad, I can start the frontend of this app, but we cannot load the data locally.
https://github.com/nlaz/flashcards-for-developers/issues/99
I'd like to load the data from the local files of json format.

**Comment by dhamaniasad** [comment]
Hey @t-cool,

I've started working on adding in the ability to load the data from JSON files instead of Airtable. Will keep you posted here!

**Comment by t-cool** [comment]
@dhamaniasad 

Thank you for your help!

I'll tell you my motivation for this.  I teach at school and I'd like to run this app on the local network.  I'll fix the IP and run this app on my local macBook and students will access to the app from their computers. 

I'll make some issues after this issue, such as registering students accounts using user is and password, etc.  I'll put some budget to this project, so it would be happy if you could help me.  

I'll tell my students that you're helping to develop this localized version.
I'd appreciate your help.

**Comment by dhamaniasad** [comment]
Hey @t-cool,

That sure sounds like an exciting use case, I'd be happy to help you with any other modifications / additions you need as well :).

I'll start working on this particular issue by forking off the Stripe branch, and submit a pull request.

Also, I'd just like to thank you for all the work you do being a teacher, I'm sure your students will appreciate this!

**Comment by t-cool** [comment]
Thank you for your comment!
I've started JS development by myself recently at freeCodeCamp.  Through this project, I'd like to improve my JS skill's too. I appreciate your help.

**Comment by dhamaniasad** [comment]
freeCodeCamp is surely a good resource for learning JavaScript, quite well rounded and comprehensive. 
Well I've been doing JS development extensively over the past few years, so hit me up if you need some tutoring :).
When you deploy this app, would you want to use Airtable for managing data or would you want to manage without it?

**Comment by dhamaniasad** [comment]
Made a pull request #2. Check it out and let me know :)

**Comment by t-cool** [comment]
@dhamaniasad 
Thank you for your help!
When I tried loading the data, I face with the following error.

```
$ node scripts/seed_db_locally.js
/Users/t-cool/Desktop/flashcards-for-developers-master/config/env.js:9
    throw new Error("The NODE_ENV environment variable is required but was not specified.");
    ^

Error: The NODE_ENV environment variable is required but was not specified.
    at module.exports (/Users/t-cool/Desktop/flashcards-for-developers-master/config/env.js:9:11)
    at Object.<anonymous> (/Users/t-cool/Desktop/flashcards-for-developers-master/config/index.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/t-cool/Desktop/flashcards-for-developers-master/scripts/load_local_collections.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
$ node scripts/seed_db_locally.js
/Users/t-cool/Desktop/flashcards-for-developers-master/config/env.js:15
    `${paths.dotenv}.${NODE_ENV}.local`,
                       ^

ReferenceError: NODE_ENV is not defined
    at module.exports (/Users/t-cool/Desktop/flashcards-for-developers-master/config/env.js:15:24)
    at Object.<anonymous> (/Users/t-cool/Desktop/flashcards-for-developers-master/config/index.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/t-cool/Desktop/flashcards-for-developers-master/scripts/load_local_collections.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
$ node --version
v10.15.0
```

**Comment by dhamaniasad** [comment]
Hey @t-cool,

Before you run the app, try running 
```bash
export NODE_ENV=development
```

As for the `DATABASE_URI` error, do you have mongo installed? By default it runs on port 27017 so you have to set the database environment variable to
```bash
MONGO_URL=mongodb://localhost:27017/flashcards
```

Where `flashcards` is the name of the database that you created. I typically use Robomongo as a GUI for mongo. 
Try the above and that should get it working.

**Comment by t-cool** [comment]
I tried your advice and the terminal says...

```
$ export NODE_ENV=development
$ MONGO_URL=mongodb://localhost:27017/flashcards
$ node scripts/seed_db_locally.js
DATABASE_URI environment variable not set.
Please set DATABASE_URI environment variable to run flashcards-for-developers
$ 
```

**Comment by dhamaniasad** [comment]
Oops sorry it's `DATABASE_URI` and also you'll need to use export before
the environment variable like so:
```bash
export DATABASE_URI=mongodb://localhost:27017/flashcards
```

**Comment by dhamaniasad** [comment]
Copy all the files from the `data_sample` folder into the `data` folder.

**Comment by t-cool** [comment]
Thank you for your advice!

I started mongod and checked database.  It seems to work... 
```
$ sudo mongod
Password:
2019-01-19T09:56:59.038+0900 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-01-19T09:56:59.056+0900 I CONTROL  [initandlisten] MongoDB starting : pid=5474 port=27017 dbpath=/data/db 64-bit host=tcool-2.local
2019-01-19T09:56:59.056+0900 I CONTROL  [initandlisten] db version v4.0.4
...
$ mongod
> use flashcards
switched to db flashcards
> db
flashcards
```

After that, I followed your steps:
```
$ export NODE_ENV=development
$ export DATABASE_URI=mongodb://localhost:27017/flashcards
$ node scripts/seed_db_locally.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../data/collections.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/t-cool/Desktop/flashcards-for-developers-master/scripts/load_local_collections.js:21:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/t-cool/Desktop/flashcards-for-developers-master/scripts/seed_db_locally.js:1:87)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
$ 
```

**Comment by t-cool** [comment]
I made it!
```
$ export NODE_ENV=development
$ export DATABASE_URI=mongodb://localhost:27017/flashcards
$ node scripts/seed_db_locally.js
Success! Number of decks written:  1
Success! Number of cards written:  7
Success! Number of collections written:  2
```

**Comment by t-cool** [comment]
@dhamaniasad 
Do you think it's possible to store all the db data in json files and make it unnecessary to use mongod to run the local server?
I think that setting up mongo server on local machine is hard for beginners like me.

**Comment by dhamaniasad** [comment]
Right, was just gonna suggest running `cp data_sample/* data/`. Are you able to see the cards in the UI now?

**Comment by t-cool** [comment]
Yes.  I can see the flashcard on the browser.
I hope that we can load flashcards directly from json files.

**Comment by t-cool** [comment]
So far, I can choose the flashcards from the top page.

**Comment by dhamaniasad** [comment]
@t-cool Yes, that would be possible, but it will require quite a bit of reworking of the code as the entire database layer would need to be replaced. And since you mentioned wanting to add user registration, that would not really be possible with plain JSON files.

**Comment by dhamaniasad** [comment]
If setting up mongo is a pain we could potentially choose to use Firebase instead, which we can also use for user registration. But I'm not sure if that's fine for you to run on your school network?

**Comment by t-cool** [comment]
I see... 
To add user registration later, we need mongod?

**Comment by dhamaniasad** [comment]
Yes, or we could use Firebase as well, so you would only need to run the Node app in that case and not a database separately, and Firebase is extremely economical as well.

**Comment by t-cool** [comment]
Yes.  I'll use it on my LAN and I'll disconnect their networks from the Internet then.

**Comment by t-cool** [comment]
Okay.  Now I understood.  
Can you implement user registration on this src?
If possible, I'll make a new issue for it.

**Comment by t-cool** [comment]
Before that, can you claim the bounty on Bountysource?
I'll release the budget.

**Comment by dhamaniasad** [comment]
Okay, in that case if internet connectivity will not be available, Firebase would not work. I can look into some file-only or non-server databases if you want to use something other than Mongo. 

I can start looking into user registration as well. 

As for the For Javascript Developers collection, I basically just loaded some sample data from the flashcardsfordevelopers.com database through their API, and while I loaded the Javascript collection, I didn't load any of the content from inside it. Do you want to load all the data available on their site?

**Comment by t-cool** [comment]
Thank you for suggesting other options.

As for Database, hopefully, I'd like to use SQLite as in Rails development because we don't need to set up DB server on the local machine.

I don't care about its sample data, I don't care about it.   I'll use this system for teaching English.   Would it be possible to load the original data as a flashcard?

```
[{
    "_id": "5b945db50d9bd6cbc6e66948",
    "airtableId": "",
    "updatedAt": "",
    "deck": "",
    "back": "In Japan.",
    "front": "Where is Tokyo in the world?",
    "__v": 0,
    "createdAt": "",
    "id": ""
}, {
    "_id": "5b945db50d9bd6cbc6e66948",
    "airtableId": "",
    "updatedAt": "",
    "deck": "",
    "back": "In the U.K.",
    "front": "Where is London in the world?",
    "__v": 0,
    "createdAt": "",
    "id": ""
}]
```

**Comment by t-cool** [comment]
@dhamaniasad 
I released the budget on Bountysource.

**Comment by t-cool** [comment]
@dhamaniasad 
Could you tell me if it's possible to implement DB parts using SQLite?
And can we add a simple user registration system (id and password) on it?
If possible, I'll make a new issue "replace MongoDB with SQLite" and post it on Bountysource.

**Comment by dhamaniasad** [comment]
> I don't care about its sample data, I don't care about it. I'll use this system for teaching English. Would it be possible to load the original data as a flashcard?

Sorry I didn't get that. Which original data are you referring to? 

And yes, it should be possible to replace the MongoDB parts with SQLite. 
And we can add a simple user registration system using email id and password on it too, replacing the current GitHub based system.

**Comment by t-cool** [comment]
I meant the data of the flashcard "JavaScript" and "Computer Science".  
I'll use this system for English learning, so I don't use those flashcards.

**Comment by dhamaniasad** [comment]
Sure, I'll add that data to the sample folder and make a PR.
